# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Peter Carragher
author: Peter Carragher [he/they]
email: yoder@cs.cmu.edu
address: >
  312 TCS Hall <br>
  Carnegie Mellon University
  Pittsburgh, PA USA
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
url: http://www.casos.cs.cmu.edu/people/bios/939.php # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  petercarragher
google_scholar: https://scholar.google.com/citations?hl=en&user=FxMWswoAAAAJ 

# Navigation links order
header_pages:
 - publications.md
 - research.md
 - cv.md

# Build settings
# markdown: kramdown
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
